name: linq
favicon: null
layout_spectrum: 0.78807
typography_spectrum: 0.18339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcfcfe'
    - '#b6d1da'
    - '#6c9aa7'
    - '#814118'
  brandStrength: 0.75
  lightness: 0.13281429279595613
  saturation: 0.9026303067803383
  rhythmicContrast: 0.5832053178455681
purpose: []
